### ISSUE TITLE
Spotify cast suggestion

### ISSUE THREAD

**Issue by Kikobeats** [mafintosh/idlecast#1]
I love this repository. Do you think that could be possible create something similar but for stream your current spotify music into chromecast?

**Comment by mafintosh** [comment]
As long as you can access it as a stream somehow it should be doable

**Comment by Kikobeats** [comment]
check this: https://github.com/bentruyman/spotify-node-stream/blob/master/app.js

More precisely, the main idea is, instead of play the current song in your desktop, cast it in the chromecast, as Youtube in chromecast mode works on mobile.

**Comment by mafintosh** [comment]
Yes then its doable. You just need to make an http server that can serve those streams and you can play them on your chromecast by passing an address to that server using my [chromecasts](https://github.com/mafintosh/chromecasts) module

**Comment by mafintosh** [comment]
You should create a new module that does this. Feel free email me, mathiasbuus@gmail.com if you have any questions when implementing that :)

**Comment by Kikobeats** [comment]
go it!
